### ISSUE TITLE
Python 2.7 interpreter installation

### ISSUE THREAD

**Issue by sk1me** [safesoftware/helm-charts#61]
Is it possible to turn on installation of optional Python 2.7 interpreter in helm charts?

**Comment by garnold54** [comment]
Unfortunately there is no setting for the in the helm chart. FME on Linux will use the system version of the Python 2.7 interpreter if it is installed. We do not install it on our engine images. In order to use the Python 2.7 interpreter in Kubernetes, you would need to create your own engine docker image that uses our image as a base, then installs the Python 2.7 interpreter. Then you can push that image to a registry and then specify the `fmeserver.image` parameters to the helm chart to point to that image.

**Comment by sk1me** [comment]
This is interesting because I went to the engine container shell (2020.1.3 version), typed python --version and got 2.7, I typed also python3 --version and got 3.6. I have also folders in python27 and python27 in /opt/...engine.../

**Comment by garnold54** [comment]
Hmm....interesting. It seems that our 2020 versions of the containers do container python 2.7, but our 2021.0 containers do not. I don't think we are explicitly adding python in either case, so something might have changed with the base image.

In any case, for 2020.1.3, with Python 2.7 being present in the engine container, I would expect FME would be able to use Python 2.7 in workspaces run by FME Server. What error are you getting when trying to run your workspace?

**Comment by sk1me** [comment]
I'm not getting any error. Just wanted to ask for option for turning on and off python 27 in helm charts. 
It seems that we have to modify docker image for that.
Thanks for heads up that 27 is not included in FME 2021!
